---
title: "Weekly expected deaths model validation"
author: "Jonas Schöley"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    df_print: paged
---

```{r setup, include=FALSE, message=FALSE}
# This script generates a report on the out-of-sample prediction
# error of the various models fitted in <01-fit_models.R>. 
# Compile the file within R via
#     rmarkdown::render('./code/visual_consistency_checks.Rmd', output_dir = './out')
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  dev.args = list(type = "cairo")
)
```

```{r load-data}
source('../code/00-init.R')
load('../out/2020-10-19-fitted_models.RData')
```


```{r init}
library(tidyverse)
library(gt)
library(pander)

dat <- list()
fig <- list()
tab <- list()
cnst <- list()

cnst$facet_ncol <- 3
cnst$names_models <- unique(fitted_models$model_name) %>% sort()
cnst$n_models <- length(cnst$names_models)
cnst$names_countries <- unique(fitted_models$country_code) %>% sort()
cnst$n_countries <- length(cnst$names_countries)
```

```{r residual-calculation}
# residuals by week and sex (aggregate over age group)
dat$residuals_by_week_and_sex <-
  fitted_models %>%
  select(-fitted_model) %>%
  group_by(country_code, cv_id, model_name, model_name_short) %>%
  group_modify(.keep = FALSE, .f = ~{
    
      # cat('Aggregate residuals of model ', unlist(.y)[3],
      #   ' on CV set ', unlist(.y)[2],
      #   ' for ', unlist(.y)[1], '\n', sep = '')
    
    unnest(.x, predictions) %>%
      # aggregate over age groups
      group_by(sample, iso_week, sex) %>%
      summarise(
        observed_deaths =
          sum(observed_deaths, na.rm = T),
        predicted_deaths =
          sum(predicted_deaths, na.rm = T),
        exposure =
          sum(exposure_pw_hmd),
        .groups = 'drop'
      )
  }) %>%
  mutate(
    residual_deaths_e =
      observed_deaths - predicted_deaths,
    residual_deaths_pe =
      (observed_deaths - predicted_deaths) / observed_deaths * 100
  ) %>%
  ungroup()

# residuals for week 27 cumulative deaths by sex
dat$residuals_cumulative_deaths_by_sex <-
  dat$residuals_by_week_and_sex %>%
  filter(sample == 'test') %>%
  arrange(country_code, cv_id, model_name, model_name_short, sex, iso_week) %>%
  group_by(country_code, cv_id, model_name, model_name_short, sex) %>%
  mutate(
    observed_cumdeaths = cumsum(observed_deaths),
    predicted_cumdeaths = cumsum(predicted_deaths),
    residual_cumdeaths_e = observed_cumdeaths - predicted_cumdeaths,
    residual_cumdeaths_pe =
      (observed_cumdeaths - predicted_cumdeaths) / observed_cumdeaths * 100
  ) %>%
  ungroup() %>%
  filter(iso_week == 26) %>%
  group_by(country_code, model_name, model_name_short, sample, sex) %>%
  summarise(
    mae = mean(abs(residual_cumdeaths_e), na.rm = TRUE),
    mape = mean(abs(residual_cumdeaths_pe), na.rm = TRUE),
    mpe = mean(residual_cumdeaths_pe, na.rm = TRUE),
    me = mean(residual_cumdeaths_e, na.rm = TRUE),
    .groups = 'drop'
  )

# weekly residuals aggregated over weeks by sex
dat$summarised_residuals <-
  dat$residuals_by_week_and_sex %>%
  group_by(country_code, model_name, model_name_short, sample, sex) %>%
  summarise(
    mae = mean(abs(residual_deaths_e), na.rm = TRUE),
    mape = mean(abs(residual_deaths_pe), na.rm = TRUE),
    mpe = mean(residual_deaths_pe, na.rm = TRUE),
    me = mean(residual_deaths_e, na.rm = TRUE),
    .groups = 'drop'
  )
```

# Results across countries

```{r w27-error-table}
tab$w27_mape <-
  dat$residuals_cumulative_deaths_by_sex %>%
  select(country_code, model_name, sex, mape) %>%
  arrange(country_code, sex) %>%
  pivot_wider(names_from = c(country_code, sex), values_from = mape) %>%
  gt() %>%
  fmt_number(2:last_col(), decimals = 1) %>% {
    cnames <- as.list(c('',
                        rep(c('F', 'M'), times = cnst$n_countries)))
    names(cnames) <- c('model_name', unlist(.[['_boxhead']]$column_label)[-1])
    
    cols_label(., .list = cnames)
  } %>%
  tab_header(
    title = 'Cumulative deaths week 10 to 27',
    subtitle = 'Mean absolute percentage error'
  ) %>%
  tab_source_note(source_note = 'Lowest error bold, highest error italic.')
for (i in 1:cnst$n_countries) {
  tab$w27_mape <-
    tab$w27_mape %>%
    tab_spanner(label = cnst$names_countries[i], columns = (i*2):(i*2+1))
}
for (i in 1:(cnst$n_countries*2)) {
  # location of rows where metric is minimal by column
  rpos_min <- apply(tab$w27_mape['_data'][[1]][,-1], 2, which.min)
    # location of rows where metric is maximal by column
  rpos_max <- apply(tab$w27_mape['_data'][[1]][,-1], 2, which.max)
  tab$w27_mape <-
    tab$w27_mape %>%
    tab_style(
      style = cell_text(weight = 'bold'),
      locations = cells_body(
        rows = rpos_min[i],
        columns = i+1
      )
    ) %>%
    tab_style(
      style = cell_text(style = 'italic'),
      locations = cells_body(
        rows = rpos_max[i],
        columns = i+1
      )
    )
}
tab$w27_mape
```

```{r weekly-error-table}
tab$weekly_mape <-
  dat$summarised_residuals %>%
  filter(sample == 'test') %>%
  select(country_code, model_name, sex, mape) %>%
  arrange(country_code, sex) %>%
  pivot_wider(names_from = c(country_code, sex), values_from = mape) %>%
  gt() %>%
  fmt_number(2:last_col(), decimals = 1) %>% {
    cnames <- as.list(c('',
                        rep(c('F', 'M'), times = cnst$n_countries)))
    names(cnames) <- c('model_name', unlist(.[['_boxhead']]$column_label)[-1])
    
    cols_label(., .list = cnames)
  } %>%
  tab_header(
    title = 'Weekly deaths week 10 to 27',
    subtitle = 'Mean absolute percentage error'
  ) %>%
  tab_source_note(source_note = 'Lowest error bold, highest error italic.')
for (i in 1:cnst$n_countries) {
  tab$weekly_mape <-
    tab$weekly_mape %>%
    tab_spanner(label = cnst$names_countries[i], columns = (i*2):(i*2+1))
}
for (i in 1:(cnst$n_countries*2)) {
    # location of rows where metric is minimal by column
  rpos_min <- apply(tab$weekly_mape['_data'][[1]][,-1], 2, which.min)
    # location of rows where metric is maximal by column
  rpos_max <- apply(tab$weekly_mape['_data'][[1]][,-1], 2, which.max)
  tab$weekly_mape <-
    tab$weekly_mape %>%
     tab_style(
      style = cell_text(weight = 'bold'),
      locations = cells_body(
        rows = rpos_min[i],
        columns = i+1
      )
    ) %>%
    tab_style(
      style = cell_text(style = 'italic'),
      locations = cells_body(
        rows = rpos_max[i],
        columns = i+1
      )
    )
}
tab$weekly_mape
```

# Results by country

```{r results-by-country}
create_section <- function(country) {
  
  # country title
  pander::pandoc.p('')
  pander::pandoc.header(country, level = 2)
  
  # data for country
  country_data <-
    dat$residuals_by_week_and_sex[
      dat$residuals_by_week_and_sex$country_code == country,
    ]
  
  pander::pandoc.p('')
  #pander::pandoc.header('Prediction error by week', level = 3)
  
  the_plot <-
    country_data %>%
    filter(sample == 'test') %>%
    ggplot(aes(x = iso_week, y = residual_deaths_e,
               color = sex, group = sex)) +
    geom_point(
      size = 0.3
    ) +
    geom_smooth(
      se = FALSE
    ) +
    geom_hline(yintercept = 0) +
    glob$ggtheme +
    facet_wrap(~model_name, ncol = cnst$facet_ncol) +
    scale_x_continuous(breaks = c(1, seq(10, 40, 5), 52)) +
    labs(x = 'Week of year', y = 'Residual error') +
    glob$MyGGplotTheme(grid = 'xy') +
    labs(
      title = paste(country, 'prediction error on test set by week (residual error)'),
      caption = 'Positive numbers indicate underestimation. Negative numbers indicate overestimation.'
    )
  
  print(the_plot)
  
  pander::pandoc.p('')
  
  the_plot <-
    country_data %>%
    filter(sample == 'test') %>%
    ggplot(aes(x = iso_week, y = residual_deaths_pe,
               color = sex, group = sex)) +
    geom_point(
      size = 0.3
    ) +
    geom_smooth(
      se = FALSE
    ) +
    geom_hline(yintercept = 0) +
    glob$ggtheme +
    facet_wrap(~model_name, ncol = cnst$facet_ncol) +
    scale_x_continuous(breaks = c(1, seq(10, 40, 5), 52)) +
    labs(x = 'Week of year', y = 'Percentage error') +
    glob$MyGGplotTheme(grid = 'xy') +
    labs(
      title = paste(country, 'prediction error on test set by week (percentage error)'),
      caption = 'Positive numbers indicate underestimation. Negative numbers indicate overestimation.'
    )
  
  print(the_plot)
  
  pander::pandoc.p('')
  
  residual_summary <-
    country_data %>%
    filter(sample == 'test') %>%
    group_by(model_name, sex) %>%
    summarise(
      mean = mean(residual_deaths_e, na.rm = TRUE),
      sd = sd(residual_deaths_e, na.rm = TRUE)
    ) %>%
    ungroup()
  
  the_plot <-
    country_data %>%
    filter(sample == 'test') %>%
    ggplot() +
    geom_vline(xintercept = 0, color = 'grey80') +
    geom_density(
      aes(
        x = residual_deaths_e, y = ..scaled..,
        color = sex, group = sex
      )
    ) +
    geom_text(
      aes(
        x = 0, y = 0.06,
        label = paste0('Mean ', formatC(mean, 3), ' SD ', formatC(sd, 3)),
        color = sex,
        group = sex
      ),
      size = 3,
      data = residual_summary,
      position = position_stack()
    ) +
    scale_x_continuous() +
    facet_wrap(~model_name, ncol = cnst$facet_ncol) +
    glob$MyGGplotTheme(grid = 'xy') +
    labs(
      title = paste(country, 'Distribution of weekly prediction errors on test set (residual error)'),
      x = 'Residual error', y = 'Scaled density'
    )
  
  print(the_plot)
  
  pander::pandoc.p('')
  
  residual_summary <-
    country_data %>%
    filter(sample == 'test') %>%
    group_by(model_name, sex) %>%
    summarise(
      mean = mean(residual_deaths_pe, na.rm = TRUE),
      sd = sd(residual_deaths_pe, na.rm = TRUE)
    ) %>%
    ungroup()
  
  the_plot <-
    country_data %>%
    filter(sample == 'test') %>%
    ggplot() +
    geom_vline(xintercept = 0, color = 'grey80') +
    geom_density(
      aes(
        x = residual_deaths_pe, y = ..scaled..,
        color = sex, group = sex
      )
    ) +
    geom_text(
      aes(
        x = 0, y = 0.06,
        label = paste0('Mean ', formatC(mean, 3), ' SD ', formatC(sd, 3)),
        color = sex,
        group = sex
      ),
      size = 3,
      data = residual_summary,
      position = position_stack()
    ) +
    scale_x_continuous() +
    facet_wrap(~model_name, ncol = cnst$facet_ncol) +
    glob$MyGGplotTheme(grid = 'xy') +
    labs(
      title = paste(country, 'Distribution of weekly prediction errors on test set (percentage error)'),
      x = 'Percentage error', y = 'Scaled density'
    )
  
  print(the_plot)

}

pander::pandoc.p('')
```

```{r, results='asis'}
for (i in cnst$names_countries) {
  create_section(i)
}
```
